version: 0.0
os: linux	
files:	
  - source: templates/index.html	  
    destination: /var/www/html/	    
hooks:	
  ApplicationStart:	 
    - location: /templates/hooks.sh   
      timeout: 300
      runas: root      
    # runas: root	     
    # - location: /scripts/start_server	    
    # timeout: 300	     
    # runas: root	      
