version: 0.0
os: linux	
files:	
  - source: templates/index.html	  
    destination: /home/ubuntu/aws-devops-pgp/templates	    
hooks:	
  AfterInstall:	 
    - location: /templates/hooks  
      timeout: 300
      runas: root      
    # runas: root	     
    # - location: /scripts/start_server	    
    # timeout: 300	     
    # runas: root	      
