custombucket = "awstestbucket1000"
table = "intellipaat"
databasehost = "mydb.cmxut22pu0bo.us-east-1.rds.amazonaws.com"
duser = "admin"
dpass = "Password1"
s3database = "intellipaat"
kapp = "http://3.228.220.21/"
